service: simple-function-service

provider:
  name: google
  runtime: nodejs
  memorySize: 128
  timeout: 15s
  project: project-name
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  
functions:
  simple-function:
    handler: handler
    name: simple-function
    events:
      - http: foo
